#!/bin/bash
# Quick Start Guide for Uitutive Docker
# This file provides a step-by-step quick start

echo "🐳 Uitutive Docker - Quick Start Guide"
echo "========================================"
echo ""
echo "This is a quick reference. For detailed info, see DOCKER_README.md"
echo ""

# Detect OS
if [[ "$OSTYPE" == "msys" || "$OSTYPE" == "cygwin" || "$OSTYPE" == "win32" ]]; then
    echo "📍 Windows Detected"
    echo ""
    echo "Option 1: Using Helper Script"
    echo "  1. Open PowerShell"
    echo "  2. cd c:\Users\rajiv\uitutive"
    echo "  3. docker-helper.bat build"
    echo "  4. docker-helper.bat up prod"
    echo "  5. docker exec ollama-service ollama pull llama2"
    echo ""
    echo "Option 2: Manual Commands"
    echo "  docker-compose build"
    echo "  docker-compose up -d"
    echo "  docker exec ollama-service ollama pull llama2"
    echo ""
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    echo "📍 Linux Detected"
    echo ""
    echo "Quick Start:"
    echo "  1. chmod +x docker-helper.sh"
    echo "  2. ./docker-helper.sh build"
    echo "  3. ./docker-helper.sh up prod"
    echo "  4. ./docker-helper.sh setup-ollama"
    echo ""
elif [[ "$OSTYPE" == "darwin"* ]]; then
    echo "📍 macOS Detected"
    echo ""
    echo "Quick Start:"
    echo "  1. chmod +x docker-helper.sh"
    echo "  2. ./docker-helper.sh build"
    echo "  3. ./docker-helper.sh up prod"
    echo "  4. ./docker-helper.sh setup-ollama"
    echo ""
fi

echo "After starting, access:"
echo "  • Frontend: http://localhost:4200"
echo "  • Backend:  http://localhost:3000/api/v1"
echo "  • Ollama:   http://localhost:11434"
echo ""
echo "Common Commands:"
echo "  docker-compose ps              # Check status"
echo "  docker-compose logs -f         # View logs"
echo "  docker-compose down            # Stop services"
echo ""
echo "Need help?"
echo "  📖 Read: DOCKER_README.md (quick reference)"
echo "  📖 Read: DOCKER_GUIDE.md (detailed guide)"
echo "  📖 Read: DOCKER_INDEX.md (navigation)"
echo ""
